language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
  - "pypy3"
matrix:
  allow_failures:
  - python: "pypy3"
  fast_finish: true

sudo: false
addons:
  apt:
    packages:
    - liblzma-dev
before_install:
  - "echo 'Installing other backports to check no conflicts...'"
  - "pip install backports.functools_partialmethod"
  - "python -c 'from backports.functools_partialmethod import partialmethod'"
  - "pip install backports.ssl"
  - "python -c 'from backports.ssl import match_hostname, __version__; print(__version__)'"
install:
  - "python setup.py install"
before_script:
  - "cd test"
script:
  - "python test_lzma.py"
  - "echo 'Checking no conflict with other backports...'"
  - "pip install backports.ssl_match_hostname"
  - "python -c 'from backports.ssl_match_hostname import match_hostname, __version__; print(__version__)'"
  - "pip install backports.csv"
  - "python -c 'from backports.cvs import list_dialects, __version__; print(__version__)'"
  - "python -c 'from backports.lzma import __version__; print(__version__)'"
