language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy"
sudo: false
addons:
  apt:
    packages:
    - liblzma-dev
install:
  - "python setup.py install"
before_script:
  - "cd test"
script:
  - "python test_lzma.py"
